### ISSUE TITLE
Executable couldn't initialize graphics pipe

### ISSUE THREAD

**Issue by ufliswuli** [GiorgiMirzashvili29/geocraft#1]
When running the executable, cmd displays following error:

Warning: unable to auto-locate config files in directory named by "<auto>etc".
Known pipe types:
(all display modules loaded.)
Traceback (most recent call last):
  File "Game.py", line 509, in <module>
    game = MyGame()
           ^^^^^^^^
  File "Game.py", line 24, in __init__
    ShowBase.__init__(self)
  File "direct\showbase\ShowBase.py", line 341, in __init__
  File "direct\showbase\ShowBase.py", line 1026, in openDefaultWindow
  File "direct\showbase\ShowBase.py", line 1061, in openMainWindow
  File "direct\showbase\ShowBase.py", line 771, in openWindow
  File "direct\showbase\ShowBase.py", line 751, in <lambda>
  File "direct\showbase\ShowBase.py", line 823, in _doOpenWindow
  File "direct\showbase\ShowBase.py", line 652, in makeDefaultPipe
  File "direct\directnotify\Notifier.py", line 130, in error
Exception: No graphics pipe is available!
Your Config.prc file must name at least one valid panda display
library via load-display or aux-display.
[4184]

**Comment by nocthedrin** [comment]
დარწმუნდით, რომ Config.prc არის თქვენი Panda3D ინსტალაციის etc დირექტორიაში.
